name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  analyze:
    strategy:
      matrix:
        package: [sqlite3]
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dart-lang/setup-dart@v1
      with:
        sdk: dev

    - name: Pub get
      run: dart pub get
      working-directory: ${{ matrix.package }}

    - name: Format
      run: dart format --set-exit-if-changed .
      working-directory: ${{ matrix.package }}
    
    - name: Analyze
      run: dart analyze
      working-directory: ${{ matrix.package }}
    
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: dart-lang/setup-dart@v1
      with:
        sdk: dev
    
    - name: install sqlite (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get install -y libsqlite3-dev
      
    - name: install sqlite (Windows)
      if: runner.os == 'Windows'
      run: choco install sqlite
    
    - name: Test
      run: |
        pub get
        dart test
      working-directory: sqlite3/

  integration_test_android:
    runs-on: macos-latest
    strategy:
      matrix:
        test:
          - flutter_libs
          - sqlcipher_flutter
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: dev
      
      - name: pub get
        working-directory: "integration_tests/${{ matrix.test }}"
        run: flutter pub get

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis # Default target is not available yet for api level 30
          arch: x86_64
          script: flutter pub run test_driver/integration_test.dart
          working-directory: "integration_tests/${{ matrix.test }}"


  # Shamelessly stolen from https://medium.com/flutter-community/run-flutter-driver-tests-on-github-actions-13c639c7e4ab
  integration_test_ios:
    runs-on: macos-latest
    steps:
      - name: List simulators
        run: "xcrun xctrace list devices"

      - name: Start simulator
        run: |
          IPHONE12=$(xcrun xctrace list devices  2>&1 | grep -m 1 "iPhone 12 Pro" | awk -F'[()]' '{print $4}')
          xcrun simctl boot $IPHONE12
      
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: dev
      
      - name: Flutter version
        run: flutter --version
      
      - name: sqlite3 driver tests
        run: "flutter pub get && flutter pub run test_driver/integration_test.dart"
        working-directory: integration_tests/flutter_libs

      - name: sqlcipher driver tests
        run: "flutter pub get && flutter pub run test_driver/integration_test.dart"
        working-directory: integration_tests/sqlcipher_flutter

  integration_test_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: dev
      - name: Setup Flutter
        run: |
          flutter config --enable-macos-desktop
          flutter --version

      - name: sqlite3 driver tests
        run: "flutter pub get && flutter pub run test_driver/integration_test.dart"
        working-directory: integration_tests/flutter_libs

      - name: sqlcipher driver tests
        run: "flutter pub get && flutter pub run test_driver/integration_test.dart"
        working-directory: integration_tests/sqlcipher_flutter
